config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :orders, only: [:create] do
    resources :payments, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :designs do
    resources :requests, only: [:index, :create, :update, :edit, :destroy, :new]
    post 'upvote', to: 'designs#upvote'
  end
  resources :requests, only: [:index, :show]
  resources :contributions, only: [:update, :edit, :destroy, :create]
  resources :projects, only: [:create, :update, :destroy, :show, :index]
  get 'dashboard', to: 'users#dashboard'
  get 'topup', to: 'pages#deals'
  get 'become-designer', to: 'pages#designerlanding'
  get 'profile', to: 'users#profile'
  get 'modal_edit_profile', to: 'users#modal_edit_profile'
  patch 'update_user_profile', to: 'users#update_user_profile', as: 'update_user_profile'
  delete 'destroy_user_profile', to: 'users#destroy', as: 'destroy_user_profile'
  get 'thingiverse', to: 'thingiverse#search_thingiverse'
  get 'thingiverse/:id', to: 'thingiverse#show', as: 'thingiverse-design'
  post 'thingiverse/create-design', to: 'thingiverse#create_design', as: 'create_thingiverse_design'
  devise_for :users, controllers: { sessions: "paths" }
  get 'users/:id/profile', to: 'users#show', as: 'user_page'
  put 'users/designer', to: 'users#designer', as: 'designer'
  resources :designers, only: [:new, :create, :index]
  post 'designers/approve', to: 'designers#approve', as: 'approve'
end

app/models/design.rb
class Design < ApplicationRecord
  belongs_to :category
  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :attachments
  has_many :requests, dependent: :destroy
  accepts_nested_attributes_for :requests
  has_many :contributions, through: :requests
  validates :name, presence: true
  validates :description, presence: true

  def self.trending
    #returns array of designs with highest number of tokens on a request
    Request.all.sort_by {|request| request.total_tokens}.reverse.map { |request| request.design }.uniq
  end
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_design, only: [:show, :update, :edit, :destroy]

  def index
    @designs = policy_scope(Design).order(created_at: :desc)
    authorize @designs

    if params[:category].present?
      @designs = Design.joins(:category).where("categories.name ILIKE :category", category: params[:category])
    end

    if params[:designname].present?
      @designs = Design.where("name ILIKE ? OR description ILIKE ? ", "%#{params[:designname]}%", "%#{params[:designname]}%")
    end
  end

  def show
    @contribution = Contribution.new
    authorize @design
  end

  def new
   @design = Design.new
   @attachment = Attachment.new
   authorize @design
  end

  def upvote
    @design = Design.find(params[:design_id])
    likes = @design.likes + 1
    @design.update(likes: likes)
    authorize @design
    respond_to do |format|
        format.html { redirect_to design_path(@design) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end

  def create
   @attachment = Attachment.new(attachment_params)
   @category = Category.find_by(name: params[:design][:category])
   @design = Design.new(design_params)
   authorize @design
   @design.category = @category
   @request = Request.new(request_params)
   @request.user = current_user
   @request.kind = :original
   @contribution = Contribution.new(contribution_params)
   @contribution.user = current_user
   if @design.save!
      @attachment.design = @design
      @attachment.save!
      @request.design = @design
      if @request.save!
        @contribution.request = @request
        if @contribution.save!
          tokens = current_user.wallet.tokens - @contribution.tokens
          current_user.wallet.update(tokens: tokens)
          redirect_to @design
        else
          flash[:alert] = "Contribution invalid."
          render 'new'
        end
      else
        flash[:alert] = "Request did not save"
        render 'new'
      end
   else
    flash[:alert] = "Design did not save"
    render 'new'
   end
 end

  def edit
    authorize @design
  end

  def update
    @design.update(design_params)
    authorize @design
    if @design.save!
      redirect_to @design
    else
      render 'edit'
    end
  end

  def destroy
    authorize @design
    @design.destroy

    redirect_to designs_path, notice: "The design has been deleted!"

  end

  private

  def set_design
    @design = Design.find(params[:id])
  end

  def design_params
    params.require(:design).permit(:name, :description)
  end

  def attachment_params
    params.require(:attachment).permit(:file)
  end

  def contribution_params
    params.require(:contribution).permit(:tokens)
  end

  def request_params
    params.require(:request).permit(:description)
  end
end

app/views/designs/create.html.erb
<h1>Designs#create</h1>
<p>Find me in app/views/designs/create.html.erb</p>

app/views/designs/destroy.html.erb
<h1>Designs#destroy</h1>
<p>Find me in app/views/designs/destroy.html.erb</p>

app/views/designs/edit.html.erb
<h1>Designs#edit</h1>
<p>Find me in app/views/designs/edit.html.erb</p>

app/views/designs/index.html.erb
<div class="container-fluid designs-index-container">
  <div class="row desings-page-row-padded">
    <div class="col-md-2 hidden-sm index-grid-padding sticky-container">
      <div class="index-categories">
        <h5>All Categories</h5>
        <hr>
        <% Category.all.each do |category| %>
          <ul class="designs-index-list categories">
            <li>
              <%= link_to category.name.capitalize, designs_path(category: category.name) %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="col-sm-12 col-md-8 index-grid-padding">
      <div class="cards-container">
        <div class="index-searchbar">
          <%= render "shared/searchbar" %>
        </div>
        <div class="index-cards-container">
          <% if @designs.presence %>
            <% @designs.each do |design|  %>
              <%= render 'shared/card', design: design %>
              <% if policy(design).edit? %>
                <%= link_to "Update", edit_design_path(design), class: "button" %>
              <% end %>
              <% if policy(design).destroy? %>
                <%= link_to "Delete", design_path(design), class: "button button-red", method: :delete, data: {confirm: "Are you sure?" } %>
              <% end %>
            <% end %>
          <% else %>
            <div>No Results found! Try a different search.</div>
          <% end %>
          <section id="thingiverse-searchbar-index">
            <div class="indexpage-thingiverse-searchbar-wrapper">
              <h3>Can't find what you want?</h3>
              <%= render 'shared/thingiverse-searchbar' %>
            </div>
          </section>
        </div>
      </div>
    </div>
    <div class="col-md-2 hidden-sm index-grid-padding sticky-container">
      <div class="index-button-wrapper">
        <% if policy(Design).create? %>
          <%= link_to "Request New Design", new_design_path, class: "button" %>
        <% end %>
      </div>
      <div class="index-button-searchthingiverse">
        <%= link_to "Search in Thingiverse", designs_path(anchor: "thingiverse-searchbar-index"), class: "button" %>
      </div>
      <div class="index-faqs">
        <h5>New to Pop?</h5>
        <hr>
        <ul class="designs-index-list">
          <li><%= link_to "How it works", "#" %></li>
          <li><%= link_to "P2P economy", "#" %></li>
          <li><%= link_to "FAQ's", "#" %></li>
          <li><%= link_to "Top Up", new_user_registration_path %></li>
        </ul>
      </div>
    </div>
  </div>
  <%= render 'shared/modal' %>
</div>
<% if user_signed_in? %>
  <%= render "shared/topup-sticky" %>
<% end %>

app/views/designs/new.html.erb
<div class="new-design-container">
  <ul id="progressbar">
    <li class="active" data-step="1">Design Photo</li>
    <li data-step="2">Design Details</li>
    <li data-step="3">Design Specifications</li>
  </ul>
  <div id="newrequest-form-carousel" class="carousel slide" data-ride="carousel" data-interval="0">
    <%= simple_form_for @attachment, url: designs_path, method: :post do |f| %>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <div class="new-request-first-container">
            <div class="upload-photo1">
              <h2>Upload your inspiration photo</h2>
                <%= f.input :file %>
                <%= f.input :file_cache, as: :hidden %>
                <a class="next-btn button" href="#newrequest-form-carousel" role="button" data-slide="next">NEXT</a>
                <hr>
                <p>Upload a photo of the thing you want it to be designed in 3D. If needed, upload a .zip to include multiple angles, features and other characteristics that will help our designers understand the job to be done.</p>
            </div>
            <div class="upload-photo2">
              <h2>For example</h2>
              <%= image_tag "upload-photo-example.jpg" %>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="new-request-second-container">
            <div class="request-title1">
              <h2>Give us some details</h2>
              <%= simple_fields_for :design do |d| %>
                <%= d.input :name %>
                <%= d.input :description, as: :text, label: "Description of Design" %>
                <%= d.input :category, collection: Category.category_name %>
              <% end %>
              <div class="request-title1-buttons">
                <a class="prev-btn button-red" href="#newrequest-form-carousel" role="button" data-slide="prev">PREVIOUS</a>
                <a class="next-btn button" href="#newrequest-form-carousel" role="button" data-slide="next">NEXT</a>
              </div>
            </div>
            <div class="request-title2">
              <%= image_tag "logo.png" %>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="new-request-third-container">
            <div class="request-description1">
              <h2>Detail the specifications for your design</h2>
              <%= simple_fields_for :request do |r| %>
                <%= r.input :description, as: :text, label: "What Changes do you want made?" %>
              <% end %>
              <%= simple_fields_for :contribution do |c| %>
                <%= c.input :tokens, required: true, input_html: { type: :text, id: "ex6", data: { slider_min: '1', slider_step: '1', slider_max: current_user.wallet.tokens, slider_value: "1" } } %>
              <% end %>
              <p>Try to be as specific as possible. Include any technical, aesthetic, mechanical, or functional detail. This is your chance to get the design exactly as you want it!</p>
              <div class="request-description-buttons">
                <a class="prev-btn button-red" href="#newrequest-form-carousel" role="button" data-slide="prev">PREVIOUS</a>
                <%= link_to "Cancel", :back, class: "button-red" %>
                <%= f.submit "Upload Design", class: "button" %>
              </div>
            </div>
            <div class="request-description2">
              <%= image_tag "new-request-description-background.png" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/designs/show.html.erb
<div class="container">
  <div class="design-showpage-wrapper">
    <div class="row">
      <div class="col-xs-12 col-show-nopadd">
        <div class="design-show-title-wrapper">
          <h2><%= @design.name %></h2>
          <div class="designshow-description">
            <p><%= @design.description %></p>
          </div>
        </div>
        <div class="backto-designindex">
          <%= link_to "Back to Results", :back %>
        </div>
      </div>
      <div class="col-sm-12 col-md-6">
        <div class="design-show-design-details">
          <div class="designshow-photos">
            <% if !@design.attachments.empty? %>
              <%= render 'shared/slideshow-designs-show' %>
            <% else %>
              <img src="https://szempatiaoptika.hu/UserFiles/Image/no-image-icon.jpg" alt="no_upload">
            <% end %>
          </div>
          <div class="like-button-wrapper">
          <% if user_signed_in? %>
            <span class="like-button-request">
              <%= link_to design_upvote_path(@design), method: :post, remote: true do %>
                <i class="fas fa-heart"></i>
              <% end %>
            </span>
            <span id="like-button"><%= @design.likes %></span>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-sm-12 col-md-6 design-show-column-container">
        <div class="requests-show-header">
          <h2>Change Requests</h2>
          <p>Contribute to the change requests that best fit your needs and boost the 3D design community!</p>
        </div>
        <div class="designshow-request-container">
          <div id="accordion">
            <div class="design-show-requests">
              <% @design.requests.each do |request| %>
              <div class="card">
                <div class="card-header" id="<%= request.description %>">
                  <h5 class="">
                    <button class="transparent-button" data-toggle="collapse" data-target="#<%= request.id %>" aria-expanded="false" aria-controls="<%= request.id %>">
                      Change Request from <%= cl_image_tag request.user.photo, class: "avatar small" %> <b><%= request.user.username %></b> <i class="fas fa-angle-down"></i>
                    </button>
                  </h5>
                </div>
                <div id="<%= request.id %>" class="collapse" aria-labelledby="<%= request.description %>" data-parent="#accordion">
                  <div class="card-body">
                    <div class="request">
                      <div class="request-kind">
                        <% if request.kind == "original" %>
                          This is a request for a <b>new</b> design
                        <% else %>
                          This is a request for an improvement on an <b>existing</b> design
                        <% end %>
                        </div>
                      <div class="request-description"><b>Description:</b> <%= request.description %></div>
                      <div class="design-show-contributions-flex">
                        <div class="contributions">
                          <span><%= request.contributions.size %> contributions</span>
                          <div class="pool">Pool: <i class="fas fa-coins"></i> <%= request.total_tokens %></div>
                        </div>
                        <div>
                          <% if !user_signed_in? %>
                            <%= link_to "Log In to contribute", new_user_session_path, class:"button" %>
                          <% else %>
                            <%= render 'shared/modal_contribute', request: request, contribution: @contribution %>
                          <% end %>
                        </div>
                        <% if user_signed_in? && current_user.admin %>
                        <div class="create-project-button">
                          <%= link_to "Create Project", projects_path(request: request), method: :post, class: "button" %>
                        <%=  %>
                        </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
            <div class="designshow-button">
              <%= link_to "Request Changes to this Design", new_design_request_path(@design), class: "button" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% if user_signed_in? %>
  <%= render "shared/topup-sticky" %>
<% end %>

app/views/designs/update.html.erb
<h1>Designs#update</h1>
<p>Find me in app/views/designs/update.html.erb</p>

app/views/designs/upvote.js.erb
console.log("hello from upvote.js.erb");
let likes = document.getElementById('like-button');
console.log(likes.innerText);
likes.innerText = <%= @design.likes %>