config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :orders, only: [:create] do
    resources :payments, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :designs do
    resources :requests, only: [:index, :create, :update, :edit, :destroy, :new]
    post 'upvote', to: 'designs#upvote'
  end
  resources :requests, only: [:index, :show]
  resources :contributions, only: [:update, :edit, :destroy, :create]
  resources :projects, only: [:create, :update, :destroy, :show, :index]
  get 'dashboard', to: 'users#dashboard'
  get 'topup', to: 'pages#deals'
  get 'become-designer', to: 'pages#designerlanding'
  get 'profile', to: 'users#profile'
  get 'modal_edit_profile', to: 'users#modal_edit_profile'
  patch 'update_user_profile', to: 'users#update_user_profile', as: 'update_user_profile'
  delete 'destroy_user_profile', to: 'users#destroy', as: 'destroy_user_profile'
  get 'thingiverse', to: 'thingiverse#search_thingiverse'
  get 'thingiverse/:id', to: 'thingiverse#show', as: 'thingiverse-design'
  post 'thingiverse/create-design', to: 'thingiverse#create_design', as: 'create_thingiverse_design'
  devise_for :users, controllers: { sessions: "paths" }
  get 'users/:id/profile', to: 'users#show', as: 'user_page'
  put 'users/designer', to: 'users#designer', as: 'designer'
  resources :designers, only: [:new, :create, :index]
  post 'designers/approve', to: 'designers#approve', as: 'approve'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_one :wallet
  has_many :contributions
  mount_uploader :photo, PhotoUploader
  after_create :create_wallet
  has_many :requests
  has_one :designer


  def full_name
    first_name + " " + last_name
  end

  def create_wallet
    Wallet.create(user: self, tokens: 0)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_after_action :verify_authorized, only: [:profile]
  def dashboard
    @orders = current_user.wallet.orders.where(state: 'paid')
    @contributions = current_user.contributions if current_user.contributions
    @projects = []
    current_user.contributions.each do |contribution|
      @projects << contribution.request.project if contribution.request.project
    end
  end

  def profile
    @user = current_user
  end

  def edit

  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update_user_profile
    @user = current_user
    authorize @user
    @user.update(item_params)
    if @user.save
      redirect_to profile_path
    else
    render 'shared/modal_edit_profile'
    end
  end

  def destroy
    @user = current_user
    authorize @user
    if @user.requests.any?
      redirect_to profile_path, alert: "You must delete all open requests before deleting your account"
    else
      @user.wallet.destroy
      @user.destroy
      redirect_to root_path, notice: "GoodBye!"
    end
  end

  def item_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :photo, :designer)
  end

end

app/views/users/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="dashboard-banner">
      <div class="col-sm-12 col-md-4 col-md-push-8 text-center">
        <%= image_tag("present-tokens.png") %>
      </div>
      <div class="col-sm-12 col-md-8 col-md-pull-4">
        <div class="sharetokens">
          <div class="sharetokens-title">
            <h2>Choose your next Creation!</h2>
          </div>
          <div class="sharetokens-description">
            <p>Give your friends 25 tokens to try PoP, and you will also get 10 tokens when they make their first contribution.</p>
          </div>
          <%= link_to "Invite Friends", "http://www.facebook.com", target: "_blank", class: "button" %>
        </div>
      </div>
    </div>
  </div>
  <div class="tabs">
    <div class="tab active" data-page="#projects">
      <!-- <a href="#projects"> -->
      Ongoing Projects
    <!-- </a> -->
    </div>
    <div class="tab" data-page="#contributions">
      <!-- <a href="#contributions"> -->
        Pending Projects
      <!-- </a> -->
    </div>
    <div class="tab" data-page="#orders">
      <!-- <a href="#orders"> -->
        Billing History
      <!-- </a> -->
    </div>
  </div>
  <div id="projects" class="tab-section active">
    <h2>Ongoing Projects</h2>
    <% if @projects.uniq.presence %>
      <div class="row">
        <% @projects.uniq.each do |project| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <%= render 'shared/project-card', project: project %>
        </div>
        <% end %>
      </div>
    <% else %>
      <h5>You have no ongoing projects! Search for a design and start creating your new projects <%= link_to "here", designs_path %></h5>
    <% end %>
  </div>
  <div id="contributions" class="tab-section">
    <h2 class="contributions-tab-title">Requests Awaiting Designer</h2>
    <% if @contributions.order(created_at: :desc).first(10).presence %>
      <% @contributions.order(created_at: :desc).first(10).each do |contribution| %>
        <div class="row">
          <div class="col-xs-5 col-tabs-nopadding">
            <div class="contribution-intab-details">
              <h6><b>Your Contribution:</b> <%= contribution.tokens %> tokens</h6>
              <div style="overflow: hidden;text-overflow: ellipsis;display: -webkit-box;-webkit-box-orient: vertical;-webkit-line-clamp: 3;"><b>Change Request:</b> <%= contribution.request.description %></div>
            </div>
          </div>
          <div class="col-xs-7 col-tabs-nopadding">
            <div class="contribution-designs-card">
              <%= render 'shared/card', design: contribution.request.design %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <h5>You have no pending projects! Search for a design and start creating your new projects <%= link_to "here", designs_path %></h5>
    <% end %>
  </div>
  <div id="orders" class="tab-section">
    <h2>Billing History</h2>
    <% if @orders.presence %>
      <div class="order">
        <% @orders.each do |order| %>
          <div><strong>Order ID: <%= order.id %></strong></div>
          <div>Status: <%= order.state %></div>
          <div>Item: <%= order.token_sku %> Tokens</div>
          <div>Amount: <%= humanized_money_with_symbol(order.amount) %></div>
        <% end %>
      </div>
    <% else %>
      <div class="nobilling-history">
        <h5>You haven't topped up your wallet yet! Get your tokens <%= link_to "here", topup_path %></h5>

      </div>
    <% end %>
  </div>
</div>
 <% if current_user.admin? %>
    <%= link_to "See PoP Designers", designers_path, class: "button" %>
<% end %>
<% if user_signed_in? %>
  <%= render "shared/topup-sticky" %>
<% end %>

app/views/users/profile.html.erb
<div class="container">
  <div class="profile-card-container">
    <h2>Your Profile:</h2>
    <div class="profile-card-layout">
      <div class="profile-card-line"><hr></div>
      <div class="profile-avatar text-center">
        <%= cl_image_tag @user.photo, class: "avatar large" %>
      </div>
      <div class="profile-username">Username: <%= @user.username %></div>
      <div class="profile-card-line"><hr></div>
      <div class="profile-name">Full name: <%= @user.full_name %></div>
      <div class="profile-card-line"><hr></div>
      <div class="profile-email">Email: <%= @user.email %></div>
      <div class="profile-card-line"><hr></div>
      <div>Contributions: <%= @user.contributions.size %></div>
      <div class="profile-card-line"><hr></div>
      <div>3D printer: <%= @user.printer %></div>
      <div class="profile-card-line"><hr></div>
      <div class="profile-card-actions">
        <button type="button" class="button" data-toggle="modal" data-target="#myModal">Edit Profile</button>
        <%= link_to "reset password", edit_user_registration_path, class: "button" %>
        <%= render 'shared/modal_edit_profile' %>
        <%= link_to "Delete", destroy_user_profile_path, data: { confirm: "Are you sure you want to delete your account?" }, method: :delete, class: "button-red" %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/topup-sticky" %>

app/views/users/show.html.erb
<div class="container">
  <div class="profile-card-container">
    <% if current_user == @user %>
      <h2>Your Profile</h2>
    <% else %>
      <h2><%= @user.username %></h2>
    <% end %>
    <div class="profile-card-layout text-center">
      <div class="profile-card-line"><hr></div>
        <div class="profile-avatar text-center">
          <%= cl_image_tag @user.photo, class: "avatar large" %>
        </div>
        <div class="profile-username">Username: <%= @user.username %></div>
        <div class="profile-card-line"><hr></div>
        <div class="profile-name"><%= @user.full_name %></div>
        <div class="profile-card-line"><hr></div>
        <% if @user.designer %>
            <div><%= @user.designer.description %></div>
            <div class="profile-card-line"><hr></div>
            <div><%= @user.designer.experience %></div>
            <div class="profile-card-line"><hr></div>
            <div>Website:</div>
            <div><%= link_to @user.designer.website, "#{@user.designer.website}", target: "_blank" %></div>
        <% else %>
          <div>Contributions: <%= @user.contributions.size %></div>
          <% if @user.printer.presence %>
          <div class="profile-card-line"><hr></div>
          <div class="profile-email-other">3D Printer: <%= @user.printer %></div>
          <% end %>
        <% end %>
        <% if current_user == @user %>
          <div class="profile-card-line"><hr></div>
          <div class="profile-card-actions">
            <button type="button" class="button" data-toggle="modal" data-target="#myModal">Edit Profile</button>
            <%= link_to "reset password", edit_user_registration_path, class: "button" %>
            <%= render 'shared/modal_edit_profile' %>
            <%= link_to "Delete", destroy_user_profile_path, data: { confirm: "Are you sure you want to delete your account?" }, method: :delete, class: "button-red" %>
          <% else %>
            <div class="profile-card-return-action"><%= link_to "Back", :back, class:"button" %></div>
          </div>
        <% end %>
    </div>
  </div>
</div>
<%= render "shared/topup-sticky" %>
<!-- if current user display Your Profile
else display <%= current_user.id %> profile -->