config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :orders, only: [:create] do
    resources :payments, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :designs do
    resources :requests, only: [:index, :create, :update, :edit, :destroy, :new]
    post 'upvote', to: 'designs#upvote'
  end
  resources :requests, only: [:index, :show]
  resources :contributions, only: [:update, :edit, :destroy, :create]
  resources :projects, only: [:create, :update, :destroy, :show, :index]
  get 'dashboard', to: 'users#dashboard'
  get 'topup', to: 'pages#deals'
  get 'become-designer', to: 'pages#designerlanding'
  get 'profile', to: 'users#profile'
  get 'modal_edit_profile', to: 'users#modal_edit_profile'
  patch 'update_user_profile', to: 'users#update_user_profile', as: 'update_user_profile'
  delete 'destroy_user_profile', to: 'users#destroy', as: 'destroy_user_profile'
  get 'thingiverse', to: 'thingiverse#search_thingiverse'
  get 'thingiverse/:id', to: 'thingiverse#show', as: 'thingiverse-design'
  post 'thingiverse/create-design', to: 'thingiverse#create_design', as: 'create_thingiverse_design'
  devise_for :users, controllers: { sessions: "paths" }
  get 'users/:id/profile', to: 'users#show', as: 'user_page'
  put 'users/designer', to: 'users#designer', as: 'designer'
  resources :designers, only: [:new, :create, :index]
  post 'designers/approve', to: 'designers#approve', as: 'approve'
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'banner-background.jpg' %>);">
  <div class="banner-container">
    <div class="banner-content">
      <h1 class="title-shadow"> The new way to get the 3D designs you need</h1>
      <p class="text-big">PoP allows you to collectively raise pools of token-based rewards to improve or generate professional-grade 3D designs.</p>
    </div>
    <div class="banner-searchbar-container">
      <%= render "shared/searchbar" %>
    </div>
  </div>
</div>

app/views/shared/_designer-banner.html.erb
<div class="designer-banner" style="background-image: url(<%= image_path 'veado.jpg' %>);">
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <div class="designer-banner-content">
        <h1>Get Paid for your 3D Designs</h1>
        <p>Your skills are worth something. Browse through user's requests, accept the challenge and get your share of the rewards pool.</p>
        <div>
          <%= link_to "Sign Up", new_designer_path, class: "button" %>
        </div>
      </div>
    </div>
    <div class="designer-banner-fade"></div>
  </div>
</div>

app/views/shared/_designers_sign_up.html.erb
<%= simple_form_for @designer do |f| %>
<% if !user_signed_in? %>
<div>Already have a PoP account?</div>
<%= link_to "Sign in", new_user_session_path %>
<%= simple_fields_for :user do |u| %>
<%= u.input :first_name, required: true %>
<%= u.input :last_name, required: true %>
<%= u.input :email, required: true %>
<% end %>
<% end %>
<%= f.input :description, label: "Describe yourself", required: true %>
<%= f.input :experience, label: "Tell us about your Design Experience", required: true %>
<%= f.input :website, label: "Website/Portfolio" %>
<%= f.input :thingiverse_username %>
<%= f.input :linkdin, label: "Linkedin" %>
<% if !user_signed_in? %>
<%= simple_fields_for :user do |u| %>
<%= u.input :username, label: "Create a PoP username" %>
<%= u.input :password, label: "Create a password", required: true %>
<%= u.input :password_confirmation, required: true %>
<% end %>
<% end %>
<%= f.submit "Submit Application", class: "button" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible <%= "alert-fixed" if action_name == "home" %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible <%= "alert-fixed" if action_name == "home" %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_home_page_popular_card.html.erb
<div class="home-popular-container">
  <%= link_to design_path(design) do %>
  <div class="home-popular-image">
    <% if design.attachments.presence %>
    <%= cl_image_tag design.attachments.first.file %>
    <% else %>
      <img src="https://szempatiaoptika.hu/UserFiles/Image/no-image-icon.jpg" alt="no_upload">
    <% end %>
  </div>
  <div class="home-popular-title">
    <h4><%= design.name %></h4>
  </div>
  <div class="home-popular-description">
    <p><%= design.description %></p>
  </div>
  <div class="home-popular-date">
    <p><%= design.requests.first.created_time_ago %></p>
  </div>
  <% end %>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="shareModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="shareModalLabel">Share</h4>
      </div>
      <div class="modal-body">
        <p>Share it and get more people to contribute!</p>
        <div class="modal-share">
          <i class="fab fa-facebook"></i>
          <i class="fab fa-twitter-square"></i>
          <i class="fas fa-envelope"></i>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_contribute.html.erb
<!-- Trigger the modal with a button -->
<button type="button" class="button" data-toggle="modal" data-target="#modal<%= request.id %>">Contribute</button>
<!-- Modal -->
<div id="modal<%= request.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-body">
        <p>Would you like to contribute to this design?</p>
        <p>Please enter the amount of tokens you would like to contribute:</p>
        <% if current_user.wallet.tokens > 0 %>
          <%= render 'shared/contributionform', request:request, contribution:@contribution %>
          <% else %>
          <div><hr>
            Uh Oh! No tokens... Top Up to contribute <%= link_to "Top Up", topup_path, class:"button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_edit_profile.html.erb
<!-- Trigger the modal with a button -->

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
  <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Profile</h4>
      </div>
      <%= simple_form_for(@user, as: current_user, url: update_user_profile_path, html: { method: :patch }) do |f| %>
        <%= f.error_notification %>
      <div class="modal-body">
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :first_name, value: @user.first_name %>
        <%= f.input :last_name,value: @user.last_name %>
        <%= f.input :email, value: @user.email %>
        <%= f.input :username, value: @user.username %>
        <%= f.button :submit, "Update", class: "button", redirect_to: profile_path %>
        <span></span>
        <%= link_to "cancel", profile_path(current_user), class: "button-red" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-white">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <div class="navbar-logo">
      <%= image_tag "logo.png" %>
      The Pool of Printables
    </div>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if !user_signed_in? %>
      <%= link_to "Become a Designer", become_designer_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% else %>
      <% if !current_user.designer %>
        <%= link_to "Become a Designer", become_designer_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% else %>
        <div class="navbar-wagon-item navbar-wagon-link">
      <div class="dropdown">
        <div class="dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">Designers</div>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Profile", profile_path %></li>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Your Projects", projects_path(designer: current_user.designer) %></li>
          <li><%= link_to "Accept New Project", requests_path, class: "navbar-wagon-item navbar-wagon-link-white" %></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
      <% end %>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to "Request New Design", new_design_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to topup_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <i class="fas fa-coins"></i>
        <span style="font-weight: 600;"><%= current_user.wallet.tokens %></span>
      <% end %>
    <% end %>
    <% if !user_signed_in? %>
      <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Log In", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

    <!-- Profile picture with dropdown list -->
    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
           <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Profile", profile_path %></li>
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <% if current_user.is_designer %>
            <li><%= link_to "Your Projects", projects_path(designer: current_user.designer) %></li>
            <% end %>
            <li><%= link_to "Browse Designs", designs_path %></li>
            <li><%= link_to "Request New Design", new_design_path %></li>
            <li><%= link_to "Top Up Wallet", topup_path %></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <% if user_signed_in? %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Profile", profile_path %></li>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Browse Designs", designs_path %></li>
          <li><%= link_to "Request New Design", new_design_path %></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <%= link_to "Sign Up", new_user_registration_path, class:"navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Log In", new_user_session_path, class:"navbar-wagon-item navbar-wagon-link" %>
          <li><%= link_to "Browse Designs", designs_path %></li>
          <li><%= link_to "Request New Design", new_design_path %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_request-card.html.erb
<div class="request-card-wrapper">
  <div class="request-card-container">

    <div class="request-card-header">
      <span class="request-card-avatar-link">
        <%= link_to user_page_path(request.user) do  %>
        <span class="request-card-avatar">
          <!-- design or request users avatar -->
          <%= cl_image_tag request.user.photo, class: "avatar small" %>
        </span>
        <span class="request-card-name">
          <!-- user-name -->
          <%= request.user.username %>
        </span>
        <% end %>
      </span>
      <span class="request-card-category">
        <!-- design/request category -->
        <%= request.design.category.name %>
      </span>
      <span class="request-card-timespan">
        <!-- • date_created - date now -->
        <%= request.created_time_ago %>
      </span>
    </div>

    <div class="request-card-body">
      <%= link_to request, class: "request-card-details-header" do %>
      <div>
        <!-- design image -->
        <% if request.design.attachments.presence %>
        <%= cl_image_tag request.design.attachments.first.file , class: "request-card-image" %>
        <% else %>
        <img src="https://res.cloudinary.com/lancekrp/image/upload/v1534162640/no_image.png" alt="" class="request-card-image">
        <% end %>
      </div>
      <div class="request-card-details">
        <div>
          <div class="request-card-title">
            <!-- Title of Design or Request (new or change) -->
            <h3><%= request.design.name %></h3>
          </div>
          <div class="request-card-description">
            <div class="request-card-description-text">
              <%= request.description %>
            </div>
          </div>
        </div>
        <% end %>
        <div class="request-card-footer">

          <div class="request-card-pool">
            <!-- Aggregated amount of rewards -->
            <button type="button"  class="transparent-button" data-container="body" data-toggle="popover" data-placement="bottom" data-content="Approximately €<%= request.total_tokens/5 %>">
               <%= request.total_tokens %> <i class="fas fa-coins"></i> <i class="fas fa-caret-down"></i>
            </button>
          </div>
          <div class="request-card-contributors">
            <!-- number of contributors -->
            <span class="hovered"><i class="fas fa-users"></i> <%= request.contributions.size %></span>
          </div>
          <div class="request-card-share">
            <!-- button to share in FB/Twitter to power visibility, make modal or dropdown to share -->
            <button type="" class="transparent-button" data-toggle="modal" data-target="#shareModal"><i class="fas fa-share-square"></i></button>
          </div>

        </div>
      </div>
    </div>
    <hr>
  </div>
</div>

app/views/shared/_slideshow-designs-show.html.erb
<div class="w3-content" style="max-width:1200px">
  <% @design.attachments.each do |attachment| %>
      <%= cl_image_tag(attachment.file, :transformation=>[ {:width=>555, :height=>500, :crop=>"fill"}], class: "mySlides") %>
  <% end %>

  <div class="w3-row-padding w3-section">
    <% @design.attachments.each_with_index do |attachment, index| %>
      <div class="w3-col s4">
        <img class="demo w3-opacity w3-hover-opacity-off" src="<%= cl_image_path attachment.file, :transformation=>[ {:width=>100, :height=>60, :crop=>"fill"}] %>" style="width:100%" onclick="currentDiv(<%= index + 1 %>)">
      </div>
    <% end %>
  </div>
</div>



<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function currentDiv(n) {
  showDivs(slideIndex = n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
     dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
  }
  x[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " w3-opacity-off";
}
</script>

app/views/shared/_thingiverse-slideshow-design-show.html.erb
<div class="w3-content" style="max-width:1200px">
  <% @thing.images.each do |photo| %>
      <%= image_tag(photo["sizes"][13]["url"], class: "mySlides", size: "555x500") %>
  <% end %>

  <div class="w3-row-padding w3-section">
    <% @thing.images.each_with_index do |photo, index| %>
      <div class="w3-col s4">
        <img class="demo w3-opacity w3-hover-opacity-off" src="<%= image_path photo["sizes"][8]["url"] %>" style="width:90%" onclick="currentDiv(<%= index + 1 %>)">
      </div>
    <% end %>
  </div>
</div>



<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function currentDiv(n) {
  showDivs(slideIndex = n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
     dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
  }
  x[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " w3-opacity-off";
}
</script>

app/views/shared/_topup-sticky.html.erb
<div class="sticky-topup">
  <%= link_to topup_path, class: "topup-style" do %>
    <i class="fas fa-coins"></i>
  <% end %>
</div>

app/views/shared/_transparent-navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <div class="navbar-logo navbar-logo-white">
    <%= image_tag "logo.png" %>
    <span>The Pool of Printables</span>
  </div>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if !user_signed_in? %>
    <%= link_to "Become a Designer", become_designer_path, class: "navbar-wagon-item navbar-wagon-link-white" %>
    <% else %>
    <% if !current_user.is_designer %>
    <%= link_to "Become a Designer", become_designer_path, class: "navbar-wagon-item navbar-wagon-link-white" %>
    <% else %>
    <div class="navbar-wagon-item navbar-wagon-link-white">
      <div class="dropdown">
        <div class="dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">Designers</div>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Profile", profile_path %></li>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Your Projects", projects_path(designer: current_user.designer) %></li>
          <li><%= link_to "Accept New Project", requests_path, class: "navbar-wagon-item navbar-wagon-link-white" %></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% end %>
    <% end %>

    <% if user_signed_in? %>
    <%= link_to "Request New Design", new_design_path, class: "navbar-wagon-item navbar-wagon-link-white" %>
    <%= link_to topup_path, class: "navbar-wagon-item navbar-wagon-link-white" do %>
    <i class="fas fa-coins"></i>
    <span style="font-weight: 600;"><%= current_user.wallet.tokens %></span>
    <% end %>
    <% end %>

    <% if !user_signed_in? %>
    <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link-white" %>
    <%= link_to "Log In", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link-white" %>
    <% end %>

    <!-- Profile picture with dropdown list -->
    <% if user_signed_in? %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
       <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
       <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Profile", profile_path %></li>
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <% if current_user.is_designer %>
        <li><%= link_to "Your Projects", projects_path(designer: current_user.designer) %></li>
        <% end %>
        <li><%= link_to "Browse Designs", designs_path %></li>
        <li><%= link_to "Request New Design", new_design_path %></li>
        <li><%= link_to "Top Up Wallet", topup_path %></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <% end %>
</div>

<!-- Dropdown appearing on mobile only -->
<% if user_signed_in? %>
<div class="navbar-wagon-item hidden-md hidden-lg">
  <div class="dropdown">
    <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li><%= link_to "Profile", profile_path %></li>
      <li><%= link_to "Dashboard", dashboard_path %></li>
      <li><%= link_to "Browse Designs", designs_path %></li>
      <li><%= link_to "Request New Design", new_design_path %></li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
        <%= t(".sign_out", default: "Log out") %>
        <% end %>
      </li>
    </ul>
  </div>
</div>
<% else %>
<div class="navbar-wagon-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <%= link_to "Sign Up", new_user_registration_path, class:"navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Log In", new_user_session_path, class:"navbar-wagon-item navbar-wagon-link" %>
      <li><%= link_to "Browse Designs", designs_path %></li>
      <li><%= link_to "Request New Design", new_design_path %></li>
    </ul>
  </div>
</div>
<% end %>
</div>