config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :orders, only: [:create] do
    resources :payments, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :designs do
    resources :requests, only: [:index, :create, :update, :edit, :destroy, :new]
    post 'upvote', to: 'designs#upvote'
  end
  resources :requests, only: [:index, :show]
  resources :contributions, only: [:update, :edit, :destroy, :create]
  resources :projects, only: [:create, :update, :destroy, :show, :index]
  get 'dashboard', to: 'users#dashboard'
  get 'topup', to: 'pages#deals'
  get 'become-designer', to: 'pages#designerlanding'
  get 'profile', to: 'users#profile'
  get 'modal_edit_profile', to: 'users#modal_edit_profile'
  patch 'update_user_profile', to: 'users#update_user_profile', as: 'update_user_profile'
  delete 'destroy_user_profile', to: 'users#destroy', as: 'destroy_user_profile'
  get 'thingiverse', to: 'thingiverse#search_thingiverse'
  get 'thingiverse/:id', to: 'thingiverse#show', as: 'thingiverse-design'
  post 'thingiverse/create-design', to: 'thingiverse#create_design', as: 'create_thingiverse_design'
  devise_for :users, controllers: { sessions: "paths" }
  get 'users/:id/profile', to: 'users#show', as: 'user_page'
  put 'users/designer', to: 'users#designer', as: 'designer'
  resources :designers, only: [:new, :create, :index]
  post 'designers/approve', to: 'designers#approve', as: 'approve'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :request
  belongs_to :designer

  validates :designer, presence: true
  validates :request, presence: true
  validates :accepted_price, presence: true

  enum status: [:designing, :validating, :validated]

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
    @contributors = []
    @project.request.contributions.each do |contribution|
      @contributors << contribution.user
    end
    authorize @project
  end

  def index
    @projects = policy_scope(Project).where(designer_id: params[:designer].to_i)
    authorize @projects
  end

  def create
    @request = Request.find(params[:request].to_i)
    @project = Project.new(accepted_price: @request.total_tokens)
    @project.designer = current_user.designer
    @project.request = @request
    authorize @project
    if @project.save!
      redirect_to @project
    else
      render 'designs#show'
    end
  end

  def update
    authorize @project
  end

  def destroy
    @project = Project.find(params[:id])
    authorize @project
    @project.destroy
    redirect_to dashboard_path
  end
end

app/views/projects/index.html.erb
<div class="container">
  <h3>Your Projects</h3>
  <% if @projects.presence %>
  <div class="row">
    <% @projects.each do |project| %>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <%= render 'shared/project-card', project: project %>
    </div>
    <% end %>
  </div>
  <% else %>
  <h5>You don't have any projects yet! Search open requests and get paid for your creations <%= link_to "here", requests_path %></h5>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="container project-show-container">
<div class="project-show-header-wrapper">
  <h2>Project: <%= @project.request.design.name %></h2>
</div>

<div class="container">
  <div class="row project-show-content-row">
    <div class="col-xs-12 col-sm-6">
      <div>
        <% if @project.file %>
          <%= cl_image_tag @project.file, class: "project-file" %>
        <% else %>
        <div class="project-status-project-show">Project Status: <%= @project.status %></div>
          <img src="https://res.cloudinary.com/lancekrp/image/upload/v1534162640/no_image.png" alt="no_upload" style: width 100% >

        <% end %>
      </div>
      <% if policy(@project).update? && !@project.file %>
        <div class="project-show-upload-area">
        <h3>Your contributors are waiting!</h3>
        <form method="POST" action="" enctype="multipart/form-data">
        <strong>Upload file:</strong>
        <input type="file" name="file" />
        <input type="submit" value="Upload" class="button" />
        </form>
      </div>
      <% end %>
      <% if @project.request.kind == :improve %>
        <%= link_to "See original design", design_path(@project.request.design.id), class: "button" %>
      <% end %>
    </div>

    <div class="col-xs-12 col-sm-6">
      <div class="project-show-project-details-wrapper">
        <div>
          <p>Designer for this project is:</p>
          <div>
            <%= link_to user_page_path(@project.designer.user) do  %>
              <%= cl_image_tag @project.designer.user.photo, class: "avatar large" %>
              <%= @project.designer.user.full_name %>
            <% end %>
          </div>
        </div>
        <div>
          <h4>Request description:</h4>
          <%= @project.request.description %>
        </div>
      </div>
      <div class="project-show-project-details-project-footer-project">
        <p><strong>Pool amount: <%= @project.accepted_price %></strong></p>
        <p>This project was made possible thanks to:</p>
        <% @contributors.uniq.each do |contributor| %>
          <%= cl_image_tag contributor.photo, class: "avatar" %>
        <% end %>

        <% if policy(@project).destroy? %>
          <%= link_to "Delete", project_path(@project), class: "button button-red", method: :delete, data: {confirm: "Are you sure?" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
<% if user_signed_in? %>
  <%= render "shared/topup-sticky" %>
<% end %>